ALTER TABLE users ADD COLUMN username_changed_at INTEGER;
ALTER TABLE users ADD COLUMN lang TEXT;
ALTER TABLE tokens ADD COLUMN payload TEXT;
ALTER TABLE users ADD COLUMN tour_visto INTEGER;
ALTER TABLE users ADD COLUMN plan TEXT;
