// Las Comprehensive Rules solo existen en ingles. Los jugadores preguntan en
// castellano. Este mapa traduce la terminologia oficial antes de buscar, que es
// lo que hace que la recuperacion funcione.
//
// Las claves van en minusculas y sin tildes (asi es como normaliza el
// tokenizador). Las frases largas se sustituyen antes que las palabras sueltas.

export const ES_EN = {
  // Zonas
  "campo de batalla": "battlefield",
  "zona de mando": "command zone",
  "cementerio": "graveyard",
  "biblioteca": "library",
  "mano": "hand",
  "exilio": "exile exiled",
  "pila": "stack",
  "zona": "zone",

  // Tipos de carta
  "criatura": "creature",
  "hechizo": "spell",
  "conjuro": "sorcery",
  "instantaneo": "instant",
  "encantamiento": "enchantment",
  "artefacto": "artifact",
  "tierra": "land",
  "tierra basica": "basic land",
  "batalla": "battle",
  "planeswalker": "planeswalker",
  "ficha": "token",
  "permanente": "permanent",
  "emblema": "emblem",
  "aura": "aura",
  "equipo": "equipment",
  "vehiculo": "vehicle",
  "saga": "saga",

  // Costes y mana
  "mana": "mana",
  "coste de mana": "mana cost",
  "valor de mana": "mana value",
  "coste generico": "generic cost",
  "coste alternativo": "alternative cost",
  "coste adicional": "additional cost",
  "reduccion de coste": "cost reduction",
  "pagar": "pay",
  "reserva de mana": "mana pool",
  "vaciado de mana": "mana pool empties",
  "identidad de color": "color identity",
  "indicador de color": "color indicator",
  "incoloro": "colorless",

  // Acciones
  "lanzar": "cast casting",
  "jugar": "play",
  "activar": "activate activated",
  "resolver": "resolve resolution",
  "contrarrestar": "counter countered counterspell",
  "robar": "draw",
  "descartar": "discard",
  "sacrificar": "sacrifice",
  "destruir": "destroy",
  "exiliar": "exile",
  "regenerar": "regenerate",
  "girar": "tap tapped",
  "tapear": "tap tapped",
  "enderezar": "untap untapped",
  "buscar": "search",
  "barajar": "shuffle",
  "revelar": "reveal",
  "poner en juego": "enters the battlefield",
  "entra al campo de batalla": "enters the battlefield",
  "deja el campo de batalla": "leaves the battlefield",
  "muere": "dies",
  "transformar": "transform",
  "voltear": "turn face up flip",
  "boca abajo": "face down",
  "boca arriba": "face up",
  "pelear": "fight",
  "anexar": "attach",
  "equipar": "equip",
  "encantar": "enchant",
  "copiar": "copy",
  "mezclar": "shuffle",

  // Combate
  "combate": "combat",
  "atacar": "attack attacking",
  "atacante": "attacking creature attacker",
  "bloquear": "block blocking",
  "bloqueador": "blocking creature blocker",
  "bloqueado": "blocked",
  "sin bloquear": "unblocked",
  "declarar atacantes": "declare attackers step",
  "declarar bloqueadores": "declare blockers step",
  "dano": "damage",
  "dano de combate": "combat damage",
  "dano letal": "lethal damage",
  "orden de dano": "damage assignment order",
  "asignar dano": "assign combat damage",
  "primer golpe": "first strike",
  "doble golpe": "double strike",
  "arrollar": "trample",
  "vigilancia": "vigilance",
  "prisa": "haste",
  "volar": "flying",
  "alcance": "reach",
  "toque mortal": "deathtouch",
  "vinculo vital": "lifelink",
  "amenaza": "menace",
  "miedo": "fear",
  "defensor": "defender",
  "destello": "flash",
  "indestructible": "indestructible",
  "proteccion": "protection",
  "antimaleficio": "hexproof",
  "velo": "shroud",
  "mal de ojo": "shroud",
  "resistencia a": "protection from",
  "atraviesa": "trample",

  // Turnos y fases
  "turno": "turn",
  "fase": "phase",
  "paso": "step",
  "prioridad": "priority",
  "mantenimiento": "upkeep step",
  "fase principal": "main phase",
  "fase de combate": "combat phase",
  "inicio de combate": "beginning of combat step",
  "final de combate": "end of combat step",
  "paso final": "end step",
  "final del turno": "end step",
  "limpieza": "cleanup step",
  "turno adicional": "extra turn",
  "fase adicional": "extra phase",
  "pasar el turno": "pass priority",

  // Habilidades
  "habilidad": "ability",
  "habilidad activada": "activated ability",
  "habilidad disparada": "triggered ability",
  "habilidad estatica": "static ability",
  "habilidad de mana": "mana ability",
  "habilidad de lealtad": "loyalty ability",
  "habilidad desencadenada": "triggered ability",
  "disparar": "trigger triggers triggered",
  "se dispara": "triggers",
  "palabra clave": "keyword",
  "accion de palabra clave": "keyword action",
  "objetivo": "target targets targeting",
  "objetivo legal": "legal target",
  "sin objetivos legales": "illegal target countered",

  // Efectos
  "efecto": "effect",
  "efecto continuo": "continuous effect",
  "efecto de reemplazo": "replacement effect",
  "efecto de prevencion": "prevention effect",
  "capa": "layer",
  "capas": "layers",
  "marca de tiempo": "timestamp",
  "dependencia": "dependency",
  "restriccion": "restriction",

  // Estado del juego
  "acciones basadas en el estado": "state-based actions",
  "accion basada en el estado": "state-based actions",
  "regla de leyendas": "legend rule",
  "leyenda": "legendary legend rule",
  "vida": "life total",
  "puntos de vida": "life total",
  "ganar vida": "gain life",
  "perder vida": "lose life",
  "ganar la partida": "wins the game",
  "perder la partida": "loses the game",
  "empate": "draw the game",
  "contador": "counter counters",
  "contadores": "counters",
  "contador de veneno": "poison counter",
  "veneno": "poison counter",
  "contador de energia": "energy counter",
  "contador rad": "rad counter",
  "lealtad": "loyalty counter",
  "fuerza": "power",
  "resistencia": "toughness",
  "caracteristica": "characteristic",
  "tipo de carta": "card type",
  "subtipo": "subtype",
  "supertipo": "supertype",
  "controlador": "controller controls",
  "propietario": "owner owns",
  "oponente": "opponent",
  "fuente": "source",
  "activo": "active player",
  "jugador activo": "active player",

  // Inicio de partida
  "mulligan": "mulligan",
  "mano inicial": "opening hand",
  "reserva": "sideboard",
  "banquillo": "sideboard",
  "mazo": "deck",
  "construccion de mazo": "deck construction",

  // Commander y variantes
  "comandante": "commander",
  "dano de comandante": "commander damage",
  "impuesto de comandante": "commander tax",
  "monarca": "monarch",
  "iniciativa": "initiative",
  "mazmorra": "dungeon",
  "dia y noche": "day night",
  "gigante de dos cabezas": "two-headed giant",
  "multijugador": "multiplayer",
  "todos contra todos": "free-for-all",
  "rango de influencia": "range of influence",
  "companero": "companion",
  "juego limitado": "limited",
  "sellado": "sealed deck",
  "draft": "booster draft",
};

// Abreviaturas y jerga que usan los jugadores en cualquier idioma.
export const SLANG = {
  "etb": "enters the battlefield",
  "ltb": "leaves the battlefield",
  "sba": "state-based actions",
  "edh": "commander",
  "2hg": "two-headed giant",
  "cmc": "mana value converted mana cost",
  "mv": "mana value",
  "gy": "graveyard",
  "bf": "battlefield",
  "pw": "planeswalker",
  "tuck": "shuffle into library",
  "bounce": "return to hand",
  "wipe": "destroy all creatures",
  "board wipe": "destroy all creatures",
  "stax": "restriction",
  "fizzle": "countered illegal target",
  "blink": "exile return battlefield",
  "flicker": "exile return battlefield",
  "ping": "deals damage",
};

export const STOPWORDS = new Set(
  (
    // castellano
    "a al algo alguna algunas alguno algunos ante antes como con contra cual cuales cuando de del desde donde dos el ella " +
    "ellas ellos en entre era eran es esa esas ese eso esos esta estan estas este esto estos fue fueron ha hace hacer han " +
    "hasta hay la las le les lo los mas me mi mientras muy nada ni no nos o os otra otras otro otros para pero poco por " +
    "porque que quien se sea si sin sobre solo son su sus tambien tan tanto te tiene tienen todo todos tu un una uno unos " +
    "y ya puedo puede pueden podria puedes debo debe deben tengo tienes tengo hago haces cuanto cuantos cual pasa ocurre " +
    // ingles
    "a an and are as at be been but by can could do does for from had has have how i if in into is it its may might must " +
    "of on or should than that the their then there these they this those to was were what when where which who will with " +
    "would you your"
  ).split(/\s+/)
);
